export const pageCopy = {
  ko: {
    nav: { proof: 'PROOF', work: 'WORK', experience: 'EXPERIENCE', cta: 'WORK WITH ME ↗', language: 'EN' },
    hero: { eyebrow: "[ HELLO, I'M WOOJIN ]", title: '모두가 AI를 쉽게, 최피티.', titleLines: ['모두가 AI를 쉽게,', '최피티.'], lede: '새로운 AI 제품을 사람들이 이해하고, 직접 써보고, 결과를 만들게 합니다.', primary: 'SELECTED WORK', secondary: 'B2B INQUIRY ↗', metricsLabel: '주요 성과' },
    proof: { index: '01 / PROOF LEDGER', title: ['숫자는 맥락과 함께', '보여줍니다.'] },
    work: { index: '02 / SELECTED WORK', title: ['새로운 기술을', '사람이 쓰는 결과로.'], fields: ['CONTEXT', 'RESPONSIBILITY', 'SYSTEM', 'RESULT'] },
    experience: { index: '03 / EXPERIENCE', title: ['콘텐츠, 성장, 운영,', '그리고 연구.'] },
    profile: { index: '04 / PROFILE', title: ['안녕하세요,', '최우진입니다.'], paragraphs: ['저는 새로운 AI를 어렵게 설명하기보다, 사람들이 직접 써보고 결과를 만들 수 있게 바꿉니다.', 'Choi.GPT에서는 복잡한 기능을 짧고 실용적인 콘텐츠로 풀어내고, 기업에서는 콘텐츠·크리에이터·데이터를 연결해 실제 성장으로 이어지게 합니다.', '기술을 소개하는 사람보다, 사람들이 기술을 실제로 쓰게 만드는 사람에 가깝습니다.'] },
    contact: { index: '05 / CONTACT', title: ['새로운 AI를 사람들이', '실제로 쓰게 만들고 싶다면.'], cta: "LET'S WORK TOGETHER ↗", socials: ['LINKEDIN', 'INSTAGRAM'] },
    footer: { copyright: '© 2026 CHOI DEPT.', location: 'SEOUL / KOREA', top: 'BACK TO TOP ↑' },
  },
  en: {
    nav: { proof: 'PROOF', work: 'WORK', experience: 'EXPERIENCE', cta: 'WORK WITH ME ↗', language: 'KO' },
    hero: { eyebrow: "[ HELLO, I'M WOOJIN ]", title: 'Making AI easy for everyone.', titleLines: ['Making AI easy', 'for everyone.'], lede: 'I turn new AI products into clear experiences people can understand, try, and use to make real outcomes.', primary: 'SELECTED WORK', secondary: 'B2B INQUIRY ↗', metricsLabel: 'Selected proof' },
    proof: { index: '01 / PROOF LEDGER', title: ['Numbers need context.', 'Here is the context.'] },
    work: { index: '02 / SELECTED WORK', title: ['Turning new technology', 'into something people use.'], fields: ['CONTEXT', 'RESPONSIBILITY', 'SYSTEM', 'RESULT'] },
    experience: { index: '03 / EXPERIENCE', title: ['Content, growth, operations,', 'and research.'] },
    profile: { index: '04 / PROFILE', title: ['Hello,', "I'm Woojin Choi."], paragraphs: ['I make new AI easier to try and easier to turn into useful outcomes.', 'Through Choi.GPT, I translate complex features into practical content. For companies, I connect content, creators, and data to measurable growth.', 'I am less interested in explaining technology than in helping people actually use it.'] },
    contact: { index: '05 / CONTACT', title: ['If you want people to', 'actually use new AI.'], cta: "LET'S WORK TOGETHER ↗", socials: ['LINKEDIN', 'INSTAGRAM'] },
    footer: { copyright: '© 2026 CHOI DEPT.', location: 'SEOUL / KOREA', top: 'BACK TO TOP ↑' },
  },
};

export const personas = [
  { id: 'creator', index: '01', title: 'AI Creator', label: 'AI CREATOR', image: '/assets/characters/dark.webp', alt: '검은 옷을 입고 태블릿을 든 최피티 픽셀 캐릭터', accent: 'creator', description: '복잡한 AI 워크플로를 누구나 바로 써볼 수 있는 한국어 콘텐츠로 바꿉니다.', chips: ['14K+ FOLLOWERS', '5M+ VIEWS', '32%+ ENGAGEMENT'], copy: { ko: { title: 'AI Creator', label: 'AI CREATOR', description: '복잡한 AI 워크플로를 누구나 바로 써볼 수 있는 한국어 콘텐츠로 바꿉니다.', alt: '검은 옷을 입고 태블릿을 든 최피티 픽셀 캐릭터', chips: ['14K+ FOLLOWERS', '5M+ VIEWS', '32%+ ENGAGEMENT'] }, en: { title: 'AI Creator', label: 'AI CREATOR', description: 'I turn complex AI workflows into practical Korean content people can try immediately.', alt: 'Pixel character of Woojin Choi in black clothes holding a tablet', chips: ['14K+ FOLLOWERS', '5M+ VIEWS', '32%+ ENGAGEMENT'] } } },
  { id: 'beauty', index: '02', title: 'Beauty & Growth', label: 'BEAUTY INFLUENCER', image: '/assets/characters/field.webp', alt: '뷰티 제품과 스마트폰을 든 최피티 픽셀 캐릭터', accent: 'beauty', description: '콘텐츠 제작과 크리에이터 협업, 성과 데이터를 다음 크리에이티브 결정으로 연결합니다.', chips: ['160K MONTHLY VIEWS', '+500% TIKTOK VIEWS', '2.4X REACH'], copy: { ko: { title: 'Beauty & Growth', label: 'BEAUTY INFLUENCER', description: '콘텐츠 제작과 크리에이터 협업, 성과 데이터를 다음 크리에이티브 결정으로 연결합니다.', alt: '뷰티 제품과 스마트폰을 든 최피티 픽셀 캐릭터', chips: ['160K MONTHLY VIEWS', '+500% TIKTOK VIEWS', '2.4X REACH'] }, en: { title: 'Beauty & Growth', label: 'BEAUTY INFLUENCER', description: 'I connect beauty content, creator partnerships, and performance signals to the next creative decision.', alt: 'Pixel character of Woojin Choi holding a beauty product and a smartphone', chips: ['160K MONTHLY VIEWS', '+500% TIKTOK VIEWS', '2.4X REACH'] } } },
  { id: 'student', index: '03', title: 'Student & Researcher', label: 'UNIVERSITY STUDENT', image: '/assets/characters/hood.webp', alt: '후드와 청바지를 입은 최피티 픽셀 캐릭터', accent: 'student', description: '미디어커뮤니케이션과 데이터애널리틱스를 공부하며 실행 가능한 AI 평가 방법을 연구합니다.', chips: ['MEDIA + DATA', 'INCHON NATIONAL UNIVERSITY', '2024–2028'], copy: { ko: { title: 'Student & Researcher', label: 'UNIVERSITY STUDENT', description: '미디어커뮤니케이션과 데이터애널리틱스를 공부하며 실행 가능한 AI 평가 방법을 연구합니다.', alt: '후드와 청바지를 입은 최피티 픽셀 캐릭터', chips: ['MEDIA + DATA', 'INCHON NATIONAL UNIVERSITY', '2024–2028'] }, en: { title: 'Student & Researcher', label: 'UNIVERSITY STUDENT', description: 'I study media communication and data analytics while researching practical ways to evaluate AI systems.', alt: 'Pixel character of Woojin Choi in a hoodie and jeans', chips: ['MEDIA + DATA', 'INCHON NATIONAL UNIVERSITY', '2024–2028'] } } },
  { id: 'kkami', index: '04', title: "Kkami's Dad", label: "KKAMI'S DAD", image: '/assets/characters/neutral.webp', alt: '검은 강아지 까미와 함께 서 있는 최피티 픽셀 캐릭터', accent: 'kkami', description: '대시보드 밖의 생활에서도 관찰하고 기록하며, 새로운 도구를 평범한 하루에 직접 시험합니다.', chips: ['DAILY OBSERVER', 'TRAVEL NOTES', 'WITH KKAMI'], copy: { ko: { title: "Kkami's Dad", label: "KKAMI'S DAD", description: '대시보드 밖의 생활에서도 관찰하고 기록하며, 새로운 도구를 평범한 하루에 직접 시험합니다.', alt: '검은 강아지 까미와 함께 서 있는 최피티 픽셀 캐릭터', chips: ['DAILY OBSERVER', 'TRAVEL NOTES', 'WITH KKAMI'] }, en: { title: "Kkami's Dad", label: "KKAMI'S DAD", description: 'Away from dashboards, I observe, document, and test new tools in the texture of everyday life.', alt: 'Pixel character of Woojin Choi standing with his black dog Kkami', chips: ['DAILY OBSERVER', 'TRAVEL NOTES', 'WITH KKAMI'] } } },
];

export const headlineMetrics = [
  { value: '14K+', label: 'FOLLOWERS', context: 'Choi.GPT', publication: 'public' },
  { value: '5M+', label: 'ORGANIC VIEWS', context: 'Choi.GPT', publication: 'public' },
  { value: '32%+', label: 'ENGAGEMENT RATE', context: 'Choi.GPT', publication: 'public' },
];

export const cases = [
  { id: 'choigpt', number: '01', title: 'Choi.GPT Viral Content', eyebrow: 'AI CREATOR / B2C', context: '바이럴 포맷과 후킹 A/B 테스트로 새로운 AI 제품을 한국 사용자가 이해하고 바로 시험할 수 있게 만드는 콘텐츠 채널.', responsibility: '바이럴 포맷 설계, 후킹 A/B 테스트, CTA 설계, 기획, 제작, 발행, 성과 분석.', system: 'MARKET → TARGET → HOOK → PRACTICAL EXAMPLE → NEXT ACTION', result: '14K+ followers · 5M+ views · 32%+ engagement · 5K+ average reactions · 10 AI/SaaS collaborations', links: [{ label: 'INSTAGRAM', href: 'https://www.instagram.com/choi.gpt.ai/' }, { label: 'NEWTAKE PR', href: 'https://www.instagram.com/choi.gpt.ai/reel/Db2pyX9yrNp/' }, { label: 'MORPHIC AD', href: 'https://www.instagram.com/choi.gpt.ai/reel/Da5XpUcyMxL/' }], copy: { ko: { title: 'Choi.GPT Viral Content', eyebrow: 'AI CREATOR / B2C', context: '바이럴 포맷과 후킹 A/B 테스트로 새로운 AI 제품을 한국 사용자가 이해하고 바로 시험할 수 있게 만드는 콘텐츠 채널.', responsibility: '바이럴 포맷 설계, 후킹 A/B 테스트, CTA 설계, 기획, 제작, 발행, 성과 분석.', system: 'MARKET → TARGET → HOOK → PRACTICAL EXAMPLE → NEXT ACTION', result: '14K+ followers · 5M+ views · 32%+ engagement · 5K+ average reactions · 10 AI/SaaS collaborations' }, en: { title: 'Choi.GPT Viral Content', eyebrow: 'AI CREATOR / B2C', context: 'A testing ground for helping Korean audiences understand and try new AI products through viral formats.', responsibility: 'Viral format design, hook A/B testing, CTA design, planning, production, publishing, and performance analysis.', system: 'MARKET → TARGET → HOOK → PRACTICAL EXAMPLE → NEXT ACTION', result: '14K+ followers · 5M+ views · 32%+ engagement · 5K+ average reactions · 10 AI/SaaS collaborations' } } },
  { id: 'beauty-growth', number: '02', title: 'LG Household & Health Care Social Crew', eyebrow: 'BEAUTY / B2B', context: 'LG생활건강의 강남글로우, 히말라야핑크, 이자녹스, CNP 등 복수 브랜드 디지털 콘텐츠와 북미향 소셜 마케팅.', responsibility: '콘텐츠 기획·촬영·편집·발행, 광고 운영, 시딩 기획, GA4 및 인앱 인사이트 기반 KPI 개선.', system: 'CREATE → PUBLISH → READ SIGNALS → IMPROVE', result: '2.4x maximum reach · 160K monthly account views · +500% TikTok global views', links: [], copy: { ko: { title: 'LG Household & Health Care Social Crew', eyebrow: 'BEAUTY / B2B', context: 'LG생활건강의 강남글로우, 히말라야핑크, 이자녹스, CNP 등 복수 브랜드 디지털 콘텐츠와 북미향 소셜 마케팅.', responsibility: '콘텐츠 기획·촬영·편집·발행, 광고 운영, 시딩 기획, GA4 및 인앱 인사이트 기반 KPI 개선.', system: 'CREATE → PUBLISH → READ SIGNALS → IMPROVE', result: '2.4x 최대 도달률 · 월간 계정 조회수 160K · TikTok 글로벌 조회수 500% 상승' }, en: { title: 'LG Household & Health Care Social Crew', eyebrow: 'BEAUTY / B2B', context: 'Digital content and North American social marketing across LG Household & Health Care beauty brands.', responsibility: 'Content planning, shooting, editing, publishing, ad operations, seeding strategy, and KPI improvement through GA4 and in-app insights.', system: 'CREATE → PUBLISH → READ SIGNALS → IMPROVE', result: '2.4x maximum reach · 160K monthly account views · +500% TikTok global views' } } },
  { id: 'oliveyoung', number: '03', title: 'CJ Olive Young Shutterbriety PRO', eyebrow: 'BEAUTY / CREATOR', context: 'CJ올리브영 공식 App·SNS 인플루언서 프로그램에서 K-뷰티 트렌드와 실제 화장품 사용 경험을 콘텐츠로 전달.', responsibility: '월간 키워드 분석, 콘텐츠 기획, 콘티 구성, 촬영·편집, 발행, 성과 측정.', system: 'KEYWORD → CONTENT PLAN → PRODUCTION → PUBLISH → MEASURE', result: '169K cumulative views · 40+ pieces · +15% online sales · 2x conversion rate · 3 monthly best reviewer awards', links: [], copy: { ko: { title: 'CJ Olive Young Shutterbriety PRO', eyebrow: 'BEAUTY / CREATOR', context: 'CJ올리브영 공식 App·SNS 인플루언서 프로그램에서 K-뷰티 트렌드와 실제 화장품 사용 경험을 콘텐츠로 전달.', responsibility: '월간 키워드 분석, 콘텐츠 기획, 콘티 구성, 촬영·편집, 발행, 성과 측정.', system: 'KEYWORD → CONTENT PLAN → PRODUCTION → PUBLISH → MEASURE', result: '누적 조회수 169K · 누적 콘텐츠 40개+ · 온라인 매출 15% 상승 · 구매전환율 2배 · 월간 최우수 리뷰어 3회' }, en: { title: 'CJ Olive Young Shutterbriety PRO', eyebrow: 'BEAUTY / CREATOR', context: 'An official App and social creator program translating K-beauty trends into useful product stories.', responsibility: 'Monthly keyword analysis, content planning, storyboarding, shooting, editing, publishing, and measurement.', system: 'KEYWORD → CONTENT PLAN → PRODUCTION → PUBLISH → MEASURE', result: '169K cumulative views · 40+ pieces · +15% online sales · 2x conversion rate · 3 monthly best reviewer awards' } } },
  { id: 'australian-cruise', number: '04', title: 'Australian Cruise Group', eyebrow: 'GLOBAL MARKETING / B2B', context: '한국인 관광객 유치를 위해 현지 시장과 여행자 키워드를 분석하고 웹·SNS 중심의 맞춤형 마케팅을 설계.', responsibility: '시장·키워드 분석, 감성 카피, 웹페이지 개선, A/B 테스트, 디지털 프로모션 전략.', system: 'INSIGHT → MESSAGE → PAGE → A/B TEST → CONVERSION', result: '1.25x click-through rate · approximately +20% cart conversion', links: [], copy: { ko: { title: 'Australian Cruise Group', eyebrow: 'GLOBAL MARKETING / B2B', context: '한국인 관광객 유치를 위해 현지 시장과 여행자 키워드를 분석하고 웹·SNS 중심의 맞춤형 마케팅을 설계.', responsibility: '시장·키워드 분석, 감성 카피, 웹페이지 개선, A/B 테스트, 디지털 프로모션 전략.', system: 'INSIGHT → MESSAGE → PAGE → A/B TEST → CONVERSION', result: '클릭률 1.25배 증가 · 장바구니 전환율 약 20% 증가' }, en: { title: 'Australian Cruise Group', eyebrow: 'GLOBAL MARKETING / B2B', context: 'A market-led campaign to attract Korean travelers through web and social channels.', responsibility: 'Market and keyword analysis, emotional copy, web page improvement, A/B testing, and digital promotion strategy.', system: 'INSIGHT → MESSAGE → PAGE → A/B TEST → CONVERSION', result: '1.25x click-through rate · approximately +20% cart conversion' } } },
  { id: 'creator-ops', number: '05', title: 'Korea/Japan Creator Operations', eyebrow: 'CREATOR OPS / B2B', context: 'Manus Creator Program의 한국·일본 크리에이터 운영.', responsibility: '소싱, 핏 검토, 아웃리치, 온보딩, 현지화, 콘텐츠 리뷰, 운영 조율.', system: 'SOURCE → QUALIFY → ONBOARD → REVIEW → MEASURE', result: '50-candidate verified workbook · 138-profile expansion review', links: [{ label: 'MANUS PARTNER CONTENT', href: 'https://www.instagram.com/choi.gpt.ai/p/Db-LfeXkuDH/' }], copy: { ko: { title: 'Korea/Japan Creator Operations', eyebrow: 'CREATOR OPS / B2B', context: 'Manus Creator Program의 한국·일본 크리에이터 운영.', responsibility: '소싱, 핏 검토, 아웃리치, 온보딩, 현지화, 콘텐츠 리뷰, 운영 조율.', system: 'SOURCE → QUALIFY → ONBOARD → REVIEW → MEASURE', result: '검증 후보자 워크북 50명 · 확장 검토 프로필 138명' }, en: { title: 'Korea/Japan Creator Operations', eyebrow: 'CREATOR OPS / B2B', context: 'Creator operations for the Manus Creator Program across Korea and Japan.', responsibility: 'Sourcing, fit review, outreach, onboarding, localization, content review, and coordination.', system: 'SOURCE → QUALIFY → ONBOARD → REVIEW → MEASURE', result: '50-candidate verified workbook · 138-profile expansion review' } } },
];

export const experience = [
  { period: '2026–PRESENT', role: 'Creator & Builder', organization: 'Choi.GPT', type: 'creator', status: 'active', copy: { ko: { role: 'Creator & Builder', organization: 'Choi.GPT', status: '진행 중' }, en: { role: 'Creator & Builder', organization: 'Choi.GPT', status: 'active' } } },
  { period: '2026', role: 'Manus AI Viral Coach', organization: 'MuseOn.AI', type: 'freelance', status: 'completed', copy: { ko: { role: 'Manus AI Viral Coach', organization: 'MuseOn.AI', status: '완료' }, en: { role: 'Manus AI Viral Coach', organization: 'MuseOn.AI', status: 'completed' } } },
  { period: '2025–2026', role: 'Global Marketing Intern · Social Crew', organization: 'LG Household & Health Care', type: 'work', status: 'completed', copy: { ko: { role: '글로벌 마케팅 인턴 · 소셜크루', organization: 'LG생활건강', status: '완료' }, en: { role: 'Global Marketing Intern · Social Crew', organization: 'LG Household & Health Care', status: 'completed' } } },
  { period: '2025', role: 'Global Marketing Intern', organization: 'Australian Cruise Group', type: 'work', status: 'completed', copy: { ko: { role: '글로벌 마케팅 인턴', organization: 'Australian Cruise Group', status: '3개월 인턴십' }, en: { role: 'Global Marketing Intern', organization: 'Australian Cruise Group', status: '3-month internship' } } },
  { period: '2024–2025', role: 'Official Influencer · Shutterbriety PRO', organization: 'CJ Olive Young', type: 'work', status: 'completed', copy: { ko: { role: '공식 인플루언서 · 셔터브리티 PRO', organization: 'CJ올리브영', status: '1년 활동' }, en: { role: 'Official Influencer · Shutterbriety PRO', organization: 'CJ Olive Young', status: '1-year program' } } },
  { period: '2024', role: 'Marketing Participant · B.READY', organization: 'Amorepacific', type: 'work', status: 'completed', copy: { ko: { role: '마케팅 대외활동 · 비레디', organization: '아모레퍼시픽', status: '6개월 활동' }, en: { role: 'Marketing Program Participant · B.READY', organization: 'Amorepacific', status: '6-month program' } } },
  { period: '2024–2028', role: 'Media Communication & Data Analytics', organization: 'Incheon National University', type: 'education', status: 'active', copy: { ko: { role: '신문방송학 · 데이터 애널리틱스', organization: '인천대학교', status: '재학 중' }, en: { role: 'Media Communication & Data Analytics', organization: 'Incheon National University', status: 'in progress' } } },
  { period: 'RESEARCH', role: 'Harness Benchmark & Implementation Lead', organization: 'Team Computer', type: 'research', status: 'prototype / pilot calibration', copy: { ko: { role: '하네스 벤치마크 · 구현 리드', organization: 'Team Computer', status: '프로토타입 / 파일럿 보정' }, en: { role: 'Harness Benchmark & Implementation Lead', organization: 'Team Computer', status: 'prototype / pilot calibration' } } },
];

export const links = { email: 'mailto:hello@choidept.com', linkedin: 'https://www.linkedin.com/in/woojin-choi-a0989b24/', instagram: 'https://www.instagram.com/choi.gpt.ai/' };
